name: browser
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animated_snack_bar: ^0.4.0
  device_info_plus: ^11.2.2
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  intl: 0.20.2
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
flutter_intl:
  enabled: true
